plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "dimensions"

include("patreoncosmetics")
project(":patreoncosmetics").projectDir = file("addons/patreoncosmetics")

include("example-addon")
project(":example-addon").projectDir = file("addons/example-addon")

include("force-link")
project(":force-link").projectDir = file("addons/force-link")

include("horizontal-portals")
project(":horizontal-portals").projectDir = file("addons/horizontal-portals")

include("worldguard-flags")
project(":worldguard-flags").projectDir = file("addons/worldguard-flags")


include("better-portals")
project(":better-portals").projectDir = file("addons/better-portals")
include("biomes-addon")
project(":biomes-addon").projectDir = file("addons/biomes-addon")
include("bungee-addon")
project(":bungee-addon").projectDir = file("addons/bungee-addon")
include("bungee-plugin")
project(":bungee-plugin").projectDir = file("addons/bungee-plugin")
include("charge-on-use")
project(":charge-on-use").projectDir = file("addons/charge-on-use")
include("commands-on-use")
project(":commands-on-use").projectDir = file("addons/commands-on-use")
include("custom-lighter")
project(":custom-lighter").projectDir = file("addons/custom-lighter")
include("custom-worlds")
project(":custom-worlds").projectDir = file("addons/custom-worlds")
include("daylight")
project(":daylight").projectDir = file("addons/daylight")
include("hub-world")
project(":hub-world").projectDir = file("addons/hub-world")
include("ignite-by-event-2")
project(":ignite-by-event-2").projectDir = file("addons/ignite-by-event-2")
include("limited-uses")
project(":limited-uses").projectDir = file("addons/limited-uses")
include("message-on-use")
project(":message-on-use").projectDir = file("addons/message-on-use")
include("model-engine")
project(":model-engine").projectDir = file("addons/model-engine")
include("particles")
project(":particles").projectDir = file("addons/particles")
include("pasted-portals")
project(":pasted-portals").projectDir = file("addons/pasted-portals")
include("permissions")
project(":permissions").projectDir = file("addons/permissions")
include("portable-portals")
project(":portable-portals").projectDir = file("addons/portable-portals")
include("portal-tp")
project(":portal-tp").projectDir = file("addons/portal-tp")
include("random-location")
project(":random-location").projectDir = file("addons/random-location")
include("stylish-portals")
project(":stylish-portals").projectDir = file("addons/stylish-portals")
include("timed-portals")
project(":timed-portals").projectDir = file("addons/timed-portals")
include("unbreakable")
project(":unbreakable").projectDir = file("addons/unbreakable")
include("velocity-plugin")
project(":velocity-plugin").projectDir = file("addons/velocity-plugin")
include("weather")
project(":weather").projectDir = file("addons/weather")
include("portal-sounds")
project(":portal-sounds").projectDir = file("addons/portal-sounds")

